-- MySQL Script generated by MySQL Workbench
-- mar 28 dic 2021 01:24:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE USER 'labpatito'@'$' IDENTIFIED BY 'labPat123';
GRANT ALL PRIVILEGES ON * . * TO 'labpatito'@'localhost';
FLUSH PRIVILEGES;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdLabPatito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdLabPatito
-- -----------------------------------------------------
DROP DATABASE IF EXISTS DBLabPatito;
CREATE SCHEMA IF NOT EXISTS `bdLabPatito` ;
USE `bdLabPatito` ;

-- -----------------------------------------------------
-- Table `bdLabPatito`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`Cliente` (
  `CUI` VARCHAR(13) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(8) NULL,
  `Correo` VARCHAR(45) NULL,
  `NIT` VARCHAR(8) NULL,
  PRIMARY KEY (`CUI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`Empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `tipoPuesto` ENUM("Administrador", "laboratorista", "secretaria") NULL,
  `usuarioSistema` VARCHAR(45) NOT NULL,
  `passwordSistema` VARCHAR(45) NOT NULL,
  `CUI` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`Medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`Orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FechaGeneracion` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  `Empleado` INT NOT NULL,
  `Cliente` VARCHAR(13) NOT NULL,
  `MedicoReferencia` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_idx` (`Cliente` ASC) VISIBLE,
  INDEX `fk_Empleado_idx` (`Empleado` ASC) VISIBLE,
  INDEX `fk_Medico_Referenciado_idx` (`MedicoReferencia` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `bdLabPatito`.`Cliente` (`CUI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado`
    FOREIGN KEY (`Empleado`)
    REFERENCES `bdLabPatito`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Referenciado`
    FOREIGN KEY (`MedicoReferencia`)
    REFERENCES `bdLabPatito`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`Examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`Examen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreExamen` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`OrdenExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`OrdenExamen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idOrden` INT NOT NULL,
  `idExamen` INT NOT NULL,
  `costoFinal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idOrden_idx` (`idOrden` ASC) VISIBLE,
  INDEX `fk_idExamen_idx` (`idExamen` ASC) VISIBLE,
  CONSTRAINT `fk_idOrden`
    FOREIGN KEY (`idOrden`)
    REFERENCES `bdLabPatito`.`Orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idExamen`
    FOREIGN KEY (`idExamen`)
    REFERENCES `bdLabPatito`.`Examen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`DetallleOrdenExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`DetallleOrdenExamen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Resultado` VARCHAR(2048) NOT NULL,
  `Empleado` INT NOT NULL,
  `idOrdenExamen` INT NOT NULL,
  INDEX `fk_Empleado_idx` (`Empleado` ASC) VISIBLE,
  INDEX `fk_DetallleOrdenExamen_1_idx` (`idOrdenExamen` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_DetallleOrdenExamen_1`
    FOREIGN KEY (`idOrdenExamen`)
    REFERENCES `bdLabPatito`.`OrdenExamen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado1`
    FOREIGN KEY (`Empleado`)
    REFERENCES `bdLabPatito`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`ParametrosExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`ParametrosExamen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idExamen` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idExamen_idx` (`idExamen` ASC) VISIBLE,
  CONSTRAINT `fk_idExamen1`
    FOREIGN KEY (`idExamen`)
    REFERENCES `bdLabPatito`.`Examen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdLabPatito`.`ResultadoParameto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdLabPatito`.`ResultadoParameto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idParametroExamen` INT NOT NULL,
  `idDetalleOrdenExamen` INT NOT NULL,
  `valorResultado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetalleOrdenExamen_idx` (`idDetalleOrdenExamen` ASC) VISIBLE,
  INDEX `fk_ParametroExamen_idx` (`idParametroExamen` ASC) VISIBLE,
  CONSTRAINT `fk_ParametroExamen`
    FOREIGN KEY (`idParametroExamen`)
    REFERENCES `bdLabPatito`.`ParametrosExamen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleOrdenExamen`
    FOREIGN KEY (`idDetalleOrdenExamen`)
    REFERENCES `bdLabPatito`.`DetallleOrdenExamen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Empleado VALUE (1,'Abner','Hernandez','Administrador','abn','123');
INSERT INTO Empleado VALUE (2,'alberto','Lopez','Administrador','alb','123');

--muestra las tablas
SHOW TABLES;

-- descripcion de las tablas
describe Empleado